import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';

class IconsCollection {
  static Map<String, IconData> iconsCollection = {
    "running": FontAwesomeIcons.personRunning,
    "walking": FontAwesomeIcons.personWalking,
    "cycling": FontAwesomeIcons.personBiking,
    "tableTennis": FontAwesomeIcons.tableTennisPaddleBall,
    "soccer": FontAwesomeIcons.futbol,
    "baseball": FontAwesomeIcons.baseballBatBall,
    "basketball": FontAwesomeIcons.basketball,
    "bowling": FontAwesomeIcons.bowlingBall,
    "gym": FontAwesomeIcons.dumbbell,
    "vollyball": FontAwesomeIcons.volleyball,
    "football": FontAwesomeIcons.football,
    "beer": FontAwesomeIcons.beerMugEmpty,
    "bread": FontAwesomeIcons.breadSlice,
    "cup": FontAwesomeIcons.mugHot,
    "fruit": FontAwesomeIcons.lemon,
    "chilly": FontAwesomeIcons.pepperHot,
    "carrot": FontAwesomeIcons.carrot,
    "cake": FontAwesomeIcons.cakeCandles,
    "burger": FontAwesomeIcons.burger,
    "pizza": FontAwesomeIcons.pizzaSlice,
    "apple": FontAwesomeIcons.appleWhole,
    "breakfast": FontAwesomeIcons.utensils,
    "lunch": FontAwesomeIcons.bowlRice,
    "cookie": FontAwesomeIcons.cookieBite,
    "blender": FontAwesomeIcons.blender,
    "broom": FontAwesomeIcons.broom,
    "guitar": FontAwesomeIcons.guitar,
    "drum": FontAwesomeIcons.drum,
    "medicine": FontAwesomeIcons.pills,
    "syringe": FontAwesomeIcons.syringe,
    "hospital": FontAwesomeIcons.hospital,
    "prescription": FontAwesomeIcons.filePrescription,
    "stethoscope": FontAwesomeIcons.stethoscope,
    "brush": FontAwesomeIcons.brush,
    "bed": FontAwesomeIcons.bed,
    "beach": FontAwesomeIcons.umbrellaBeach,
    "school": FontAwesomeIcons.school,
    "images": FontAwesomeIcons.images,
    "fileImage": FontAwesomeIcons.fileImage,
    "camera": FontAwesomeIcons.camera,
    "sdCard": FontAwesomeIcons.sdCard,
    "tv": FontAwesomeIcons.tv,
    "call": FontAwesomeIcons.phoneVolume,
    "gaming": FontAwesomeIcons.gamepad,
    "chess": FontAwesomeIcons.chess,
    "steam": FontAwesomeIcons.steam,
    "ps": FontAwesomeIcons.playstation,
    "paintRoller": FontAwesomeIcons.paintRoller,
    "painting": FontAwesomeIcons.palette,
    "bath": FontAwesomeIcons.bath,
    "toilet": FontAwesomeIcons.toilet,
    "money": FontAwesomeIcons.sackDollar,
    "newspaper": FontAwesomeIcons.newspaper,
    "radio": FontAwesomeIcons.radio,
    "plus": FontAwesomeIcons.plus,
    "music": FontAwesomeIcons.music,
    "smoking": FontAwesomeIcons.banSmoking,
    "headphones": FontAwesomeIcons.headphones,
    "code": FontAwesomeIcons.code,
    "programming": FontAwesomeIcons.laptopCode,
    "studying": FontAwesomeIcons.bookOpen,
    "singing": FontAwesomeIcons.microphoneLines,
    "scissors": FontAwesomeIcons.scissors,
    "linkedin": FontAwesomeIcons.linkedin,
    "helmet": FontAwesomeIcons.helmetUn
    // "alarm": Icons.alarm,
    // "accessible": Icons.accessible,
    // "wallet": Icons.account_balance_wallet,
    // "profile": Icons.account_circle_sharp,
    // "add": Icons.add,
    // "agriculture": Icons.agriculture,
    // "pool": Icons.pool,
  };
}
